export const initialValues = {
  image: [""],
  title_en: "",
  title_ar: "",
  description_en: "",
  description_ar: "",
  price: "",
  store: "",
  size: "",
  color: "",
  categoryId: "",
  subCategory: "",
  brand: "",
  vendor: "",
};
